Add view to accept card token instead of full card details.
Fueled/django-rest-framework-stripe pull request #2
Opened 2016-12-28 21:52 UTC by zemekeneng

Hi @vikalpj and @akarambir,
Thanks for getting this repo updated for django 1.9 and python 3. This was very helpful!

I added a new url (w/ a view and a serializer) so that we can use stripe.js in the client, and avoid CC#'s ever hitting the server.

2016-12-29 09:42 UTC, vikalpj commented
Thanks @zemekeneng, for add the end point.

We haven't got much chance to dig into the test cases for now. The above code seems to be coming from https://github.com/Fueled/django-rest-framework-stripe/commit/0351cfe529adc9f4c59d21647067a925f1791073 and seems like it should be changed to `stripe-change-card`

2016-12-29 12:30 UTC, karambir requested changes
Just a minor fix needed. Thanks for PR :)

2016-12-29 12:30 UTC, akarambir commented on payments/api/views.py
> +                customer.update_card(token)
I think we should validate the token first as the underlying `customer.update_card` is not handling incoming error. Previously our own code was generating this token, so there was no need. But now, the token is coming from api. See here https://stripe.com/docs/api#retrieve_token

The below `try.. except stripe.CardError` also won't handle this. The error would be something like:

```python
InvalidRequestError: Request req_8tiPGLdRt: No such token: tok_invalid_test_token
```

2016-12-30 09:41 UTC, karambir approved these changes
LGTM

2016-12-30 09:41 UTC, akarambir commented on payments/api/views.py
> +                customer.update_card(token)
`StripeError` should handle this. Thanks

2016-12-30 09:42 UTC, merged